# .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias y compilar Angular
        run: |
          cd angular-todo
          npm install
          npm run build

      - name: Deploy a Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAILYMANA_9A816 }}
          channelId: live
          projectId: dailymana-9a816
          entryPoint: angular-todo  # 👈 importante: le dice al deploy dónde está firebase.json
